### ISSUE TITLE
No module named win32api

### ISSUE THREAD

**Issue by Eisblume77** [AlexEne/CCrush-Bot#4]
Hi,

when I start main.py I got the following error:

ImportError: No module named win32api

How can I install win32api on Mac?? 

pip install pypiwin32 doesn't work with error:

  Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32)

Please help. Thanks !!
Marco

**Comment by AlexEne** [comment]
Hi, 

I only tested this on windows, so most likely it doesn't work on Mac. 

If you want to use it there, you need to replace the win32 api that I use for mouse capture with something a bit more platform agnostic (or at least mac specific). 
At the time when I wrote this I couldn't find something easy to use for mouse control that's multi-platform so I just used directly the windows-specific one, but I am sure something is out there.

Thanks,
Alex

I am closing this as windows being the only supported platform is a known limitation.
