### ISSUE TITLE
Please review code, if you respect yourself

### ISSUE THREAD

**Issue by RazvanBd** [AlexEne/CCrush-Bot#8]
Hello, I hope that in the last 9 years you have managed to stop treating any matrix as a square one and to respect an x-y convention or a loop in a row-column matrix in all the code. Also the use of global variables with the same size throughout the code. I tried to adapt the code on a 5x8 game and after 2 hours I'm still not sure if the values ​​in the code are chosen correctly. It would be a great contribution if you did a code review on your own work, it is very difficult to understand this code from a public repo. Good job with the image detection, that code worked perfectly

**Comment by AlexEne** [comment]
No
